-- ====================================================================
-- TreaderAPP Database DDL Script (Sprint 0)
-- Target Schema: boot_user
-- ====================================================================

SET DEFINE OFF;

-- --------------------------------------------------------------------
-- 1. 기존 객체 정리 (DROP IF EXISTS)
-- --------------------------------------------------------------------
BEGIN
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS';
    END LOOP;
    FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE "' || s.sequence_name || '"';
    END LOOP;
END;
/

-- --------------------------------------------------------------------
-- 2. 시퀀스 생성 (22개)
-- --------------------------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BOARD         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST_FILE     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMAIL_TOKEN   START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CUSTOMER      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUST_CONTACT  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRICE_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_QUOTATION     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_QUOTATION_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SALES_ORDER   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SO_ITEM       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SHIPMENT      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SHIPMENT_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVOICE       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVENTORY_TXN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ATTACHMENT    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EXCHANGE_RATE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTIFICATION  START WITH 1 INCREMENT BY 1 NOCACHE;

-- --------------------------------------------------------------------
-- 3. 테이블 생성 (회원/게시판)
-- --------------------------------------------------------------------
CREATE TABLE MEMBER (
    MEMBER_ID         NUMBER(19)     NOT NULL,
    LOGIN_ID          VARCHAR2(50)   NOT NULL,
    PASSWORD          VARCHAR2(100)  NOT NULL,
    NAME              VARCHAR2(50)   NOT NULL,
    EMAIL             VARCHAR2(150)  NOT NULL,
    PHONE             VARCHAR2(30)   NOT NULL,
    ROLE              VARCHAR2(20)   DEFAULT 'CUSTOMER' NOT NULL,
    CUSTOMER_ID       NUMBER(19),
    DEPT              VARCHAR2(50),
    POSITION          VARCHAR2(50),
    EMAIL_VERIFIED_YN CHAR(1)        DEFAULT 'N' NOT NULL,
    PWD_TEMP_YN       CHAR(1)        DEFAULT 'N' NOT NULL,
    PWD_CHANGED_AT    TIMESTAMP,
    LAST_LOGIN_AT     TIMESTAMP,
    STATUS            VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    CREATED_BY        VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY        VARCHAR2(50),
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_MEMBER_EMAIL    UNIQUE (EMAIL),
    CONSTRAINT CK_MEMBER_ROLE   CHECK (ROLE IN ('ADMIN','SALES','CUSTOMER')),
    CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN ('PENDING','ACTIVE','DORMANT','WITHDRAWN')),
    CONSTRAINT CK_MEMBER_EV     CHECK (EMAIL_VERIFIED_YN IN ('Y','N')),
    CONSTRAINT CK_MEMBER_PT     CHECK (PWD_TEMP_YN IN ('Y','N'))
);

CREATE TABLE EMAIL_TOKEN (
    TOKEN_ID     NUMBER(19)    NOT NULL,
    MEMBER_ID    NUMBER(19)    NOT NULL,
    TOKEN        VARCHAR2(100) NOT NULL,
    PURPOSE      VARCHAR2(20)  NOT NULL,
    EXPIRES_AT   TIMESTAMP     NOT NULL,
    USED_YN      CHAR(1)       DEFAULT 'N' NOT NULL,
    CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EMAIL_TOKEN PRIMARY KEY (TOKEN_ID),
    CONSTRAINT UK_EMAIL_TOKEN UNIQUE (TOKEN),
    CONSTRAINT FK_EMAIL_TOKEN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CK_EMAIL_TOKEN_PURPOSE CHECK (PURPOSE IN ('SIGNUP','PWD_RESET'))
);

CREATE TABLE BOARD (
    BOARD_ID    NUMBER(19)   NOT NULL,
    BOARD_CODE  VARCHAR2(20) NOT NULL,
    BOARD_NAME  VARCHAR2(50) NOT NULL,
    AUTH_READ   VARCHAR2(20) DEFAULT 'ALL'    NOT NULL,
    AUTH_WRITE  VARCHAR2(20) DEFAULT 'MEMBER' NOT NULL,
    FILE_YN     CHAR(1) DEFAULT 'N' NOT NULL,
    COMMENT_YN  CHAR(1) DEFAULT 'N' NOT NULL,
    LIKE_YN     CHAR(1) DEFAULT 'Y' NOT NULL,
    PAGE_SIZE   NUMBER(3) DEFAULT 10 NOT NULL,
    SORT_ORDER  NUMBER(3) DEFAULT 1  NOT NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_ID),
    CONSTRAINT UK_BOARD_CODE UNIQUE (BOARD_CODE)
);

CREATE TABLE POST (
    POST_ID      NUMBER(19)    NOT NULL,
    BOARD_ID     NUMBER(19)    NOT NULL,
    MEMBER_ID    NUMBER(19),
    GUEST_NAME   VARCHAR2(50),
    GUEST_PWD    VARCHAR2(100),
    TITLE        VARCHAR2(200) NOT NULL,
    CONTENT      CLOB          NOT NULL,
    VIEW_CNT     NUMBER(10) DEFAULT 0 NOT NULL,
    LIKE_CNT     NUMBER(10) DEFAULT 0 NOT NULL,
    COMMENT_CNT  NUMBER(10) DEFAULT 0 NOT NULL,
    ANSWERED_YN  CHAR(1) DEFAULT 'N' NOT NULL,
    DEL_YN       CHAR(1) DEFAULT 'N' NOT NULL,
    WRITER_IP    VARCHAR2(45),
    CREATED_BY   VARCHAR2(50),
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY   VARCHAR2(50),
    UPDATED_AT   TIMESTAMP,
    CONSTRAINT PK_POST PRIMARY KEY (POST_ID),
    CONSTRAINT FK_POST_BOARD  FOREIGN KEY (BOARD_ID)  REFERENCES BOARD(BOARD_ID),
    CONSTRAINT FK_POST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CK_POST_WRITER CHECK (
        (MEMBER_ID IS NOT NULL) OR (GUEST_NAME IS NOT NULL AND GUEST_PWD IS NOT NULL)
    )
);

CREATE TABLE POST_COMMENT (
    COMMENT_ID  NUMBER(19) NOT NULL,
    POST_ID     NUMBER(19) NOT NULL,
    MEMBER_ID   NUMBER(19) NOT NULL,
    PARENT_ID   NUMBER(19),
    CONTENT     VARCHAR2(2000) NOT NULL,
    DEL_YN      CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP,
    CONSTRAINT PK_POST_COMMENT PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_COMMENT_POST   FOREIGN KEY (POST_ID)   REFERENCES POST(POST_ID),
    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_COMMENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES POST_COMMENT(COMMENT_ID)
);

CREATE TABLE POST_FILE (
    FILE_ID      NUMBER(19)    NOT NULL,
    POST_ID      NUMBER(19)    NOT NULL,
    ORIG_NAME    VARCHAR2(255) NOT NULL,
    STORED_NAME  VARCHAR2(255) NOT NULL,
    FILE_PATH    VARCHAR2(500) NOT NULL,
    CONTENT_TYPE VARCHAR2(100),
    MEDIA_TYPE   VARCHAR2(20)  NOT NULL,
    FILE_SIZE    NUMBER(19)    NOT NULL,
    DOWNLOAD_CNT NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_POST_FILE PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_POST_FILE_POST FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
    CONSTRAINT CK_POST_FILE_MEDIA CHECK (MEDIA_TYPE IN ('IMAGE','VIDEO','AUDIO','OTHER'))
);

CREATE TABLE POST_LIKE (
    POST_ID    NUMBER(19) NOT NULL,
    MEMBER_ID  NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_POST_LIKE PRIMARY KEY (POST_ID, MEMBER_ID),
    CONSTRAINT FK_LIKE_POST   FOREIGN KEY (POST_ID)   REFERENCES POST(POST_ID),
    CONSTRAINT FK_LIKE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- --------------------------------------------------------------------
-- 4. 테이블 생성 (마스터: 거래처, 제품, 단가이력, 재고)
-- --------------------------------------------------------------------
CREATE TABLE CUSTOMER (
    CUSTOMER_ID        NUMBER(19)    NOT NULL,
    CUSTOMER_CODE      VARCHAR2(8)   NOT NULL,
    NAME_EN            VARCHAR2(200) NOT NULL,
    NAME_KO            VARCHAR2(200),
    COUNTRY_CODE       CHAR(2)       NOT NULL,
    BIZ_REG_NO         VARCHAR2(50),
    ADDRESS            VARCHAR2(500),
    DEFAULT_CURRENCY   CHAR(3)  DEFAULT 'USD' NOT NULL,
    DEFAULT_INCOTERMS  VARCHAR2(10) DEFAULT 'FOB',
    PAYMENT_TERMS_CODE VARCHAR2(20) DEFAULT 'TT_30' NOT NULL,
    PAYMENT_DAYS       NUMBER(3) DEFAULT 30,
    ADVANCE_RATE       NUMBER(5,2) DEFAULT 30,
    QUOTE_VALID_DAYS   NUMBER(3) DEFAULT 30 NOT NULL,
    CREDIT_LIMIT       NUMBER(18,2),
    STATUS             VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    REMARK             VARCHAR2(1000),
    CREATED_BY         VARCHAR2(50),
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE)
);

CREATE TABLE CUSTOMER_CONTACT (
    CONTACT_ID  NUMBER(19) NOT NULL,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    NAME        VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(150),
    PHONE       VARCHAR2(50),
    POSITION    VARCHAR2(50),
    MAIN_YN     CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_CUSTOMER_CONTACT PRIMARY KEY (CONTACT_ID),
    CONSTRAINT FK_CONTACT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);

CREATE TABLE PRODUCT (
    PRODUCT_ID   NUMBER(19)    NOT NULL,
    PRODUCT_CODE VARCHAR2(50)  NOT NULL,
    NAME_EN      VARCHAR2(200) NOT NULL,
    NAME_KO      VARCHAR2(200),
    SPEC         VARCHAR2(500),
    HS_CODE      VARCHAR2(20),
    UNIT         VARCHAR2(10) DEFAULT 'EA' NOT NULL,
    MOQ          NUMBER(15,3),
    PACKAGE_TYPE VARCHAR2(50),
    QTY_PER_CTN  NUMBER(10),
    NET_WEIGHT   NUMBER(15,3),
    GROSS_WEIGHT NUMBER(15,3),
    CBM          NUMBER(15,4),
    STATUS       VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY   VARCHAR2(50),
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY   VARCHAR2(50),
    UPDATED_AT   TIMESTAMP,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT UK_PRODUCT_CODE UNIQUE (PRODUCT_CODE)
);

CREATE TABLE PRICE_HISTORY (
    PRICE_ID    NUMBER(19) NOT NULL,
    CUSTOMER_ID NUMBER(19),
    PRODUCT_ID  NUMBER(19) NOT NULL,
    CURRENCY    CHAR(3)    DEFAULT 'USD' NOT NULL,
    UNIT_PRICE  NUMBER(18,4) NOT NULL,
    INCOTERMS   VARCHAR2(10),
    MIN_QTY     NUMBER(15,3) DEFAULT 0,
    VALID_FROM  DATE NOT NULL,
    VALID_TO    DATE,
    REMARK      VARCHAR2(500),
    CREATED_BY  VARCHAR2(50),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PRICE_HISTORY PRIMARY KEY (PRICE_ID),
    CONSTRAINT FK_PRICE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_PRICE_PRODUCT  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_PRICE_PERIOD CHECK (VALID_TO IS NULL OR VALID_TO >= VALID_FROM)
);

CREATE TABLE INVENTORY (
    PRODUCT_ID    NUMBER(19) NOT NULL,
    ON_HAND_QTY   NUMBER(15,3) DEFAULT 0 NOT NULL,
    ALLOCATED_QTY NUMBER(15,3) DEFAULT 0 NOT NULL,
    SAFETY_QTY    NUMBER(15,3) DEFAULT 0 NOT NULL,
    VERSION       NUMBER(19)   DEFAULT 0 NOT NULL,
    UPDATED_AT    TIMESTAMP,
    CONSTRAINT PK_INVENTORY PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_INVENTORY_QTY CHECK (ON_HAND_QTY >= 0 AND ALLOCATED_QTY >= 0)
);

CREATE TABLE INVENTORY_TXN (
    TXN_ID     NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    TXN_TYPE   VARCHAR2(20) NOT NULL,
    QTY        NUMBER(15,3) NOT NULL,
    BEFORE_QTY NUMBER(15,3),
    AFTER_QTY  NUMBER(15,3),
    REF_TYPE   VARCHAR2(20),
    REF_ID     NUMBER(19),
    REMARK     VARCHAR2(500),
    CREATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INVENTORY_TXN PRIMARY KEY (TXN_ID),
    CONSTRAINT FK_INV_TXN_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- --------------------------------------------------------------------
-- 5. 테이블 생성 (트랜잭션: 견적, 수주, 출하, 인보이스, 입금)
-- --------------------------------------------------------------------
CREATE TABLE QUOTATION (
    QUOTATION_ID        NUMBER(19)   NOT NULL,
    QUOTE_NO            VARCHAR2(40) NOT NULL,
    REV_NO              NUMBER(3) DEFAULT 0 NOT NULL,
    ORIGIN_QUOTATION_ID NUMBER(19),
    CUSTOMER_ID         NUMBER(19)   NOT NULL,
    QUOTE_DATE          DATE         NOT NULL,
    VALID_UNTIL         DATE         NOT NULL,
    CURRENCY            CHAR(3)      DEFAULT 'USD' NOT NULL,
    INCOTERMS           VARCHAR2(10),
    PORT_OF_LOADING     VARCHAR2(100),
    PORT_OF_DISCHARGE   VARCHAR2(100),
    PAYMENT_TERMS_CODE  VARCHAR2(20),
    TOTAL_AMOUNT        NUMBER(18,2) DEFAULT 0 NOT NULL,
    EXCHANGE_RATE       NUMBER(15,4),
    STATUS              VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    REMARK              VARCHAR2(2000),
    SALES_MEMBER_ID     NUMBER(19),
    CREATED_BY          VARCHAR2(50),
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(50),
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT PK_QUOTATION PRIMARY KEY (QUOTATION_ID),
    CONSTRAINT UK_QUOTATION_NO UNIQUE (QUOTE_NO),
    CONSTRAINT FK_QUOTATION_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_QUOTATION_ORIGIN   FOREIGN KEY (ORIGIN_QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID),
    CONSTRAINT CK_QUOTATION_STATUS CHECK
        (STATUS IN ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','SUPERSEDED'))
);

CREATE TABLE QUOTATION_ITEM (
    ITEM_ID      NUMBER(19) NOT NULL,
    QUOTATION_ID NUMBER(19) NOT NULL,
    LINE_NO      NUMBER(4)  NOT NULL,
    PRODUCT_ID   NUMBER(19) NOT NULL,
    QTY          NUMBER(15,3) NOT NULL,
    UNIT_PRICE   NUMBER(18,4) NOT NULL,
    AMOUNT       NUMBER(18,2) NOT NULL,
    REMARK       VARCHAR2(500),
    CONSTRAINT PK_QUOTATION_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT UK_QUOTATION_LINE UNIQUE (QUOTATION_ID, LINE_NO),
    CONSTRAINT FK_QI_QUOTATION FOREIGN KEY (QUOTATION_ID)
        REFERENCES QUOTATION(QUOTATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_QI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_QI_QTY CHECK (QTY > 0)
);

CREATE TABLE SALES_ORDER (
    ORDER_ID           NUMBER(19)   NOT NULL,
    ORDER_NO           VARCHAR2(40) NOT NULL,
    QUOTATION_ID       NUMBER(19),
    CUSTOMER_ID        NUMBER(19)   NOT NULL,
    ORDER_DATE         DATE NOT NULL,
    REQUIRED_DATE      DATE,
    CURRENCY           CHAR(3) DEFAULT 'USD' NOT NULL,
    INCOTERMS          VARCHAR2(10),
    PORT_OF_LOADING    VARCHAR2(100),
    PORT_OF_DISCHARGE  VARCHAR2(100),
    PAYMENT_TERMS_CODE VARCHAR2(20),
    PAYMENT_DAYS       NUMBER(3),
    TOTAL_AMOUNT       NUMBER(18,2) DEFAULT 0 NOT NULL,
    STATUS             VARCHAR2(20) DEFAULT 'CONFIRMED' NOT NULL,
    PO_NO              VARCHAR2(50),
    REMARK             VARCHAR2(2000),
    SALES_MEMBER_ID    NUMBER(19),
    CREATED_BY         VARCHAR2(50),
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_SALES_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT UK_SALES_ORDER_NO UNIQUE (ORDER_NO),
    CONSTRAINT UK_SO_QUOTATION UNIQUE (QUOTATION_ID),
    CONSTRAINT FK_SO_QUOTATION FOREIGN KEY (QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID),
    CONSTRAINT FK_SO_CUSTOMER  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT CK_SO_STATUS CHECK
        (STATUS IN ('CONFIRMED','IN_PRODUCTION','PARTIALLY_SHIPPED','SHIPPED','CLOSED','CANCELLED'))
);

CREATE TABLE SALES_ORDER_ITEM (
    ITEM_ID     NUMBER(19) NOT NULL,
    ORDER_ID    NUMBER(19) NOT NULL,
    LINE_NO     NUMBER(4)  NOT NULL,
    PRODUCT_ID  NUMBER(19) NOT NULL,
    ORDERED_QTY NUMBER(15,3) NOT NULL,
    SHIPPED_QTY NUMBER(15,3) DEFAULT 0 NOT NULL,
    UNIT_PRICE  NUMBER(18,4) NOT NULL,
    AMOUNT      NUMBER(18,2) NOT NULL,
    REMARK      VARCHAR2(500),
    CONSTRAINT PK_SO_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT UK_SO_ITEM_LINE UNIQUE (ORDER_ID, LINE_NO),
    CONSTRAINT FK_SOI_ORDER   FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SOI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_SOI_SHIPPED CHECK (SHIPPED_QTY >= 0 AND SHIPPED_QTY <= ORDERED_QTY)
);

CREATE TABLE SHIPMENT (
    SHIPMENT_ID             NUMBER(19)   NOT NULL,
    SHIPMENT_NO             VARCHAR2(40) NOT NULL,
    ORDER_ID                NUMBER(19)   NOT NULL,
    TRANSPORT_MODE          VARCHAR2(10) DEFAULT 'OCEAN' NOT NULL,
    SHIP_DATE               DATE,
    ETD                     DATE,
    ETA                     DATE,
    VESSEL_NAME             VARCHAR2(100),
    VOYAGE_NO               VARCHAR2(50),
    BL_NO                   VARCHAR2(50),
    CONTAINER_NO            VARCHAR2(50),
    SEAL_NO                 VARCHAR2(50),
    CONTAINER_TYPE          VARCHAR2(20),
    AWB_NO                  VARCHAR2(50),
    FLIGHT_NO               VARCHAR2(50),
    AIRLINE                 VARCHAR2(100),
    PORT_OF_LOADING         VARCHAR2(100),
    PORT_OF_DISCHARGE       VARCHAR2(100),
    SHIPPING_MARKS          CLOB,
    TOTAL_NET_WEIGHT        NUMBER(15,3),
    TOTAL_GROSS_WEIGHT      NUMBER(15,3),
    TOTAL_CHARGEABLE_WEIGHT NUMBER(15,3),
    TOTAL_CBM               NUMBER(15,4),
    TOTAL_CARTON            NUMBER(10),
    STATUS                  VARCHAR2(20) DEFAULT 'PLANNED' NOT NULL,
    REMARK                  VARCHAR2(1000),
    CREATED_BY              VARCHAR2(50),
    CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY              VARCHAR2(50),
    UPDATED_AT              TIMESTAMP,
    CONSTRAINT PK_SHIPMENT PRIMARY KEY (SHIPMENT_ID),
    CONSTRAINT UK_SHIPMENT_NO UNIQUE (SHIPMENT_NO),
    CONSTRAINT FK_SHIPMENT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ORDER_ID),
    CONSTRAINT CK_SHIPMENT_STATUS CHECK (STATUS IN ('PLANNED','PACKED','SHIPPED','ARRIVED','CANCELLED')),
    CONSTRAINT CK_SHIPMENT_MODE   CHECK (TRANSPORT_MODE IN ('OCEAN','AIR')),
    CONSTRAINT CK_SHIPMENT_DOC CHECK (
        STATUS <> 'SHIPPED'
        OR (TRANSPORT_MODE = 'OCEAN' AND BL_NO  IS NOT NULL)
        OR (TRANSPORT_MODE = 'AIR'   AND AWB_NO IS NOT NULL)
    )
);

CREATE TABLE SHIPMENT_ITEM (
    ITEM_ID       NUMBER(19) NOT NULL,
    SHIPMENT_ID   NUMBER(19) NOT NULL,
    ORDER_ITEM_ID NUMBER(19) NOT NULL,
    PRODUCT_ID    NUMBER(19) NOT NULL,
    QTY           NUMBER(15,3) NOT NULL,
    CARTON_QTY    NUMBER(10),
    NET_WEIGHT    NUMBER(15,3),
    GROSS_WEIGHT  NUMBER(15,3),
    CBM           NUMBER(15,4),
    CONSTRAINT PK_SHIPMENT_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_SHI_SHIPMENT FOREIGN KEY (SHIPMENT_ID)
        REFERENCES SHIPMENT(SHIPMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHI_ORDER_ITEM FOREIGN KEY (ORDER_ITEM_ID) REFERENCES SALES_ORDER_ITEM(ITEM_ID),
    CONSTRAINT FK_SHI_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE INVOICE (
    INVOICE_ID         NUMBER(19)   NOT NULL,
    INVOICE_NO         VARCHAR2(40) NOT NULL,
    INVOICE_TYPE       VARCHAR2(10) NOT NULL,
    QUOTATION_ID       NUMBER(19),
    ORDER_ID           NUMBER(19),
    SHIPMENT_ID        NUMBER(19),
    ISSUE_DATE         DATE NOT NULL,
    DUE_DATE           DATE NOT NULL,
    CURRENCY           CHAR(3) NOT NULL,
    AMOUNT             NUMBER(18,2) NOT NULL,
    RATE_BASE_DATE     DATE,
    EXCHANGE_RATE      NUMBER(15,4),
    KRW_AMOUNT         NUMBER(18,2),
    PAID_AMOUNT        NUMBER(18,2) DEFAULT 0 NOT NULL,
    STATUS             VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,
    PAYMENT_TERMS_CODE VARCHAR2(20),
    PAYMENT_METHOD     VARCHAR2(20),
    LC_NO              VARCHAR2(50),
    LC_DATE            DATE,
    BANK_INFO          VARCHAR2(500),
    PUBLIC_TOKEN       VARCHAR2(64),
    CREATED_BY         VARCHAR2(50),
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR2(50),
    UPDATED_AT         TIMESTAMP,
    CONSTRAINT PK_INVOICE PRIMARY KEY (INVOICE_ID),
    CONSTRAINT UK_INVOICE_NO UNIQUE (INVOICE_NO),
    CONSTRAINT UK_INVOICE_TOKEN UNIQUE (PUBLIC_TOKEN),
    CONSTRAINT FK_INVOICE_QUOTATION FOREIGN KEY (QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID),
    CONSTRAINT FK_INVOICE_ORDER    FOREIGN KEY (ORDER_ID)    REFERENCES SALES_ORDER(ORDER_ID),
    CONSTRAINT FK_INVOICE_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT(SHIPMENT_ID),
    CONSTRAINT CK_INVOICE_TYPE   CHECK (INVOICE_TYPE IN ('PI','CI')),
    CONSTRAINT CK_INVOICE_STATUS CHECK
        (STATUS IN ('ISSUED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED')),
    CONSTRAINT CK_INVOICE_CI CHECK
        (INVOICE_TYPE <> 'CI' OR (SHIPMENT_ID IS NOT NULL AND ORDER_ID IS NOT NULL)),
    CONSTRAINT CK_INVOICE_PI CHECK
        (INVOICE_TYPE <> 'PI' OR (QUOTATION_ID IS NOT NULL OR ORDER_ID IS NOT NULL))
);

CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER(19) NOT NULL,
    INVOICE_ID NUMBER(19) NOT NULL,
    PAID_DATE  DATE NOT NULL,
    AMOUNT     NUMBER(18,2) NOT NULL,
    CURRENCY   CHAR(3) NOT NULL,
    METHOD     VARCHAR2(20),
    BANK_REF   VARCHAR2(100),
    REMARK     VARCHAR2(500),
    CREATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT FK_PAYMENT_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    CONSTRAINT CK_PAYMENT_AMOUNT CHECK (AMOUNT > 0)
);

-- --------------------------------------------------------------------
-- 6. 테이블 생성 (부속: 파일, 환율, 알림, 채번)
-- --------------------------------------------------------------------
CREATE TABLE ATTACHMENT (
    ATTACHMENT_ID NUMBER(19) NOT NULL,
    REF_TYPE      VARCHAR2(20) NOT NULL,
    REF_ID        NUMBER(19)   NOT NULL,
    DOC_TYPE      VARCHAR2(20),
    ORIG_NAME     VARCHAR2(255) NOT NULL,
    STORED_NAME   VARCHAR2(255) NOT NULL,
    FILE_PATH     VARCHAR2(500) NOT NULL,
    CONTENT_TYPE  VARCHAR2(100),
    FILE_SIZE     NUMBER(19) NOT NULL,
    CREATED_BY    VARCHAR2(50),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ATTACHMENT PRIMARY KEY (ATTACHMENT_ID),
    CONSTRAINT CK_ATTACHMENT_REF CHECK
        (REF_TYPE IN ('QUOTATION','SALES_ORDER','SHIPMENT','INVOICE'))
);

CREATE TABLE EXCHANGE_RATE (
    RATE_ID     NUMBER(19) NOT NULL,
    BASE_DATE   DATE       NOT NULL,
    CUR_UNIT    VARCHAR2(10) NOT NULL,
    CUR_NAME    VARCHAR2(50),
    DEAL_BAS_R  NUMBER(15,4) NOT NULL,
    TTB         NUMBER(15,4),
    TTS         NUMBER(15,4),
    SOURCE      VARCHAR2(30) DEFAULT 'KOREAEXIM' NOT NULL,
    FETCHED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EXCHANGE_RATE PRIMARY KEY (RATE_ID),
    CONSTRAINT UK_EXCHANGE_RATE UNIQUE (BASE_DATE, CUR_UNIT)
);

CREATE TABLE NOTIFICATION (
    NOTIF_ID   NUMBER(19) NOT NULL,
    MEMBER_ID  NUMBER(19) NOT NULL,
    NOTIF_TYPE VARCHAR2(30) NOT NULL,
    TITLE      VARCHAR2(200) NOT NULL,
    MESSAGE    VARCHAR2(1000),
    REF_TYPE   VARCHAR2(20),
    REF_ID     NUMBER(19),
    READ_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTIF_ID),
    CONSTRAINT FK_NOTIF_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE DOC_NUMBER (
    DOC_TYPE      VARCHAR2(20) NOT NULL,
    CUSTOMER_CODE VARCHAR2(8)  NOT NULL,
    YEAR_VAL      NUMBER(4)    NOT NULL,
    LAST_SEQ      NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DOC_NUMBER PRIMARY KEY (DOC_TYPE, CUSTOMER_CODE, YEAR_VAL)
);

-- --------------------------------------------------------------------
-- 7. 인덱스 생성 (13개)
-- --------------------------------------------------------------------
CREATE INDEX IX_POST_LIST      ON POST (BOARD_ID, DEL_YN, POST_ID DESC);
CREATE INDEX IX_COMMENT_POST   ON POST_COMMENT (POST_ID, DEL_YN);
CREATE INDEX IX_PRICE_LOOKUP   ON PRICE_HISTORY (PRODUCT_ID, CUSTOMER_ID, VALID_FROM);
CREATE INDEX IX_QUOTATION_CUS  ON QUOTATION (CUSTOMER_ID, QUOTE_DATE DESC);
CREATE INDEX IX_QUOTATION_ST   ON QUOTATION (STATUS, VALID_UNTIL);
CREATE INDEX IX_SO_CUS         ON SALES_ORDER (CUSTOMER_ID, ORDER_DATE DESC);
CREATE INDEX IX_SO_STATUS      ON SALES_ORDER (STATUS);
CREATE INDEX IX_SHIPMENT_ORD   ON SHIPMENT (ORDER_ID);
CREATE INDEX IX_SHIPMENT_ETD   ON SHIPMENT (ETD, STATUS);
CREATE INDEX IX_INVOICE_DUE    ON INVOICE (DUE_DATE, STATUS);
CREATE INDEX IX_INV_TXN_PROD   ON INVENTORY_TXN (PRODUCT_ID, CREATED_AT DESC);
CREATE INDEX IX_ATTACHMENT_REF ON ATTACHMENT (REF_TYPE, REF_ID);
CREATE INDEX IX_NOTIF_MEMBER   ON NOTIFICATION (MEMBER_ID, READ_YN, NOTIF_ID DESC);

-- --------------------------------------------------------------------
-- 8. 초기 마스터 데이터 INSERT
-- --------------------------------------------------------------------
-- 게시판 마스터 3종
INSERT INTO BOARD (BOARD_ID, BOARD_CODE, BOARD_NAME, AUTH_READ, AUTH_WRITE, FILE_YN, COMMENT_YN, LIKE_YN, PAGE_SIZE, SORT_ORDER)
VALUES (SEQ_BOARD.NEXTVAL, 'FREE', '공지·문의', 'ALL', 'ALL', 'N', 'N', 'Y', 10, 1);

INSERT INTO BOARD (BOARD_ID, BOARD_CODE, BOARD_NAME, AUTH_READ, AUTH_WRITE, FILE_YN, COMMENT_YN, LIKE_YN, PAGE_SIZE, SORT_ORDER)
VALUES (SEQ_BOARD.NEXTVAL, 'QNA', '거래처 Q&A', 'MEMBER', 'MEMBER', 'N', 'Y', 'Y', 10, 2);

INSERT INTO BOARD (BOARD_ID, BOARD_CODE, BOARD_NAME, AUTH_READ, AUTH_WRITE, FILE_YN, COMMENT_YN, LIKE_YN, PAGE_SIZE, SORT_ORDER)
VALUES (SEQ_BOARD.NEXTVAL, 'ARCHIVE', '자료실', 'MEMBER', 'MEMBER', 'Y', 'Y', 'Y', 10, 3);

-- 관리자 계정 (초기 비밀번호: 1234 -> BCrypt)
INSERT INTO MEMBER (MEMBER_ID, LOGIN_ID, PASSWORD, NAME, EMAIL, PHONE, ROLE, EMAIL_VERIFIED_YN, STATUS)
VALUES (SEQ_MEMBER.NEXTVAL, 'admin', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', '관리자', 'admin@example.com', '010-0000-0000', 'ADMIN', 'Y', 'ACTIVE');

COMMIT;

EXIT;
