-- ====================================================================
-- TreaderAPP Database DDL Script (Sprint 0) - MariaDB Version
-- Target Schema: treader_db
-- Converted from Oracle to MariaDB
-- ====================================================================

-- MariaDB 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS treader_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE treader_db;

-- 기존 테이블 정리
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS DOC_NUMBER;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS EXCHANGE_RATE;
DROP TABLE IF EXISTS ATTACHMENT;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS SHIPMENT_ITEM;
DROP TABLE IF EXISTS SHIPMENT;
DROP TABLE IF EXISTS SALES_ORDER_ITEM;
DROP TABLE IF EXISTS SALES_ORDER;
DROP TABLE IF EXISTS QUOTATION_ITEM;
DROP TABLE IF EXISTS QUOTATION;
DROP TABLE IF EXISTS INVENTORY_TXN;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS PRICE_HISTORY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER_CONTACT;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS POST_LIKE;
DROP TABLE IF EXISTS POST_FILE;
DROP TABLE IF EXISTS POST_COMMENT;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS EMAIL_TOKEN;
DROP TABLE IF EXISTS MEMBER;
SET FOREIGN_KEY_CHECKS = 1;

-- ====================================================================
-- 1. 회원/인증 테이블
-- ====================================================================
CREATE TABLE MEMBER (
    MEMBER_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    LOGIN_ID          VARCHAR(50)     NOT NULL,
    PASSWORD          VARCHAR(100)    NOT NULL,
    NAME              VARCHAR(50)     NOT NULL,
    EMAIL             VARCHAR(150)    NOT NULL,
    PHONE             VARCHAR(30)     NOT NULL,
    ROLE              VARCHAR(20)     DEFAULT 'CUSTOMER' NOT NULL,
    CUSTOMER_ID       BIGINT,
    DEPT              VARCHAR(50),
    POSITION          VARCHAR(50),
    EMAIL_VERIFIED_YN CHAR(1)         DEFAULT 'N' NOT NULL,
    PWD_TEMP_YN       CHAR(1)         DEFAULT 'N' NOT NULL,
    PWD_CHANGED_AT    TIMESTAMP NULL,
    LAST_LOGIN_AT     TIMESTAMP NULL,
    STATUS            VARCHAR(20)     DEFAULT 'PENDING' NOT NULL,
    CREATED_BY        VARCHAR(50),
    CREATED_AT        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY        VARCHAR(50),
    UPDATED_AT        TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBER_ID),
    UNIQUE KEY UK_MEMBER_LOGIN_ID (LOGIN_ID),
    UNIQUE KEY UK_MEMBER_EMAIL (EMAIL),
    CONSTRAINT CK_MEMBER_ROLE   CHECK (ROLE IN ('ADMIN','SALES','CUSTOMER')),
    CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN ('PENDING','ACTIVE','DORMANT','WITHDRAWN')),
    CONSTRAINT CK_MEMBER_EV     CHECK (EMAIL_VERIFIED_YN IN ('Y','N')),
    CONSTRAINT CK_MEMBER_PT     CHECK (PWD_TEMP_YN IN ('Y','N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EMAIL_TOKEN (
    TOKEN_ID     BIGINT          NOT NULL AUTO_INCREMENT,
    MEMBER_ID    BIGINT          NOT NULL,
    TOKEN        VARCHAR(100)    NOT NULL,
    PURPOSE      VARCHAR(20)     NOT NULL,
    EXPIRES_AT   TIMESTAMP       NOT NULL,
    USED_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    CREATED_AT   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (TOKEN_ID),
    UNIQUE KEY UK_EMAIL_TOKEN (TOKEN),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CK_EMAIL_TOKEN_PURPOSE CHECK (PURPOSE IN ('SIGNUP','PWD_RESET'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ====================================================================
-- 2. 게시판 테이블
-- ====================================================================
CREATE TABLE BOARD (
    BOARD_ID    BIGINT          NOT NULL AUTO_INCREMENT,
    BOARD_CODE  VARCHAR(20)     NOT NULL,
    BOARD_NAME  VARCHAR(50)     NOT NULL,
    AUTH_READ   VARCHAR(20)     DEFAULT 'ALL'    NOT NULL,
    AUTH_WRITE  VARCHAR(20)     DEFAULT 'MEMBER' NOT NULL,
    FILE_YN     CHAR(1)         DEFAULT 'N' NOT NULL,
    COMMENT_YN  CHAR(1)         DEFAULT 'N' NOT NULL,
    LIKE_YN     CHAR(1)         DEFAULT 'Y' NOT NULL,
    PAGE_SIZE   INT             DEFAULT 10 NOT NULL,
    SORT_ORDER  INT             DEFAULT 1  NOT NULL,
    PRIMARY KEY (BOARD_ID),
    UNIQUE KEY UK_BOARD_CODE (BOARD_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POST (
    POST_ID      BIGINT          NOT NULL AUTO_INCREMENT,
    BOARD_ID     BIGINT          NOT NULL,
    MEMBER_ID    BIGINT,
    GUEST_NAME   VARCHAR(50),
    GUEST_PWD    VARCHAR(100),
    TITLE        VARCHAR(200)    NOT NULL,
    CONTENT      LONGTEXT        NOT NULL,
    VIEW_CNT     INT             DEFAULT 0 NOT NULL,
    LIKE_CNT     INT             DEFAULT 0 NOT NULL,
    COMMENT_CNT  INT             DEFAULT 0 NOT NULL,
    ANSWERED_YN  CHAR(1)         DEFAULT 'N' NOT NULL,
    DEL_YN       CHAR(1)         DEFAULT 'N' NOT NULL,
    WRITER_IP    VARCHAR(45),
    CREATED_BY   VARCHAR(50),
    CREATED_AT   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (POST_ID),
    FOREIGN KEY (BOARD_ID)  REFERENCES BOARD(BOARD_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CK_POST_WRITER CHECK (
        (MEMBER_ID IS NOT NULL) OR (GUEST_NAME IS NOT NULL AND GUEST_PWD IS NOT NULL)
    ),
    INDEX IX_POST_LIST (BOARD_ID, DEL_YN, POST_ID DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POST_COMMENT (
    COMMENT_ID  BIGINT          NOT NULL AUTO_INCREMENT,
    POST_ID     BIGINT          NOT NULL,
    MEMBER_ID   BIGINT          NOT NULL,
    PARENT_ID   BIGINT,
    CONTENT     VARCHAR(2000)   NOT NULL,
    DEL_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (COMMENT_ID),
    FOREIGN KEY (POST_ID)   REFERENCES POST(POST_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (PARENT_ID) REFERENCES POST_COMMENT(COMMENT_ID),
    INDEX IX_COMMENT_POST (POST_ID, DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POST_FILE (
    FILE_ID      BIGINT          NOT NULL AUTO_INCREMENT,
    POST_ID      BIGINT          NOT NULL,
    ORIG_NAME    VARCHAR(255)    NOT NULL,
    STORED_NAME  VARCHAR(255)    NOT NULL,
    FILE_PATH    VARCHAR(500)    NOT NULL,
    CONTENT_TYPE VARCHAR(100),
    MEDIA_TYPE   VARCHAR(20)     NOT NULL,
    FILE_SIZE    BIGINT          NOT NULL,
    DOWNLOAD_CNT INT             DEFAULT 0 NOT NULL,
    CREATED_AT   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (FILE_ID),
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
    CONSTRAINT CK_POST_FILE_MEDIA CHECK (MEDIA_TYPE IN ('IMAGE','VIDEO','AUDIO','OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE POST_LIKE (
    POST_ID    BIGINT          NOT NULL,
    MEMBER_ID  BIGINT          NOT NULL,
    CREATED_AT TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (POST_ID, MEMBER_ID),
    FOREIGN KEY (POST_ID)   REFERENCES POST(POST_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ====================================================================
-- 3. 마스터 테이블 (거래처, 제품, 단가이력, 재고)
-- ====================================================================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID        BIGINT          NOT NULL AUTO_INCREMENT,
    CUSTOMER_CODE      VARCHAR(8)      NOT NULL,
    NAME_EN            VARCHAR(200)    NOT NULL,
    NAME_KO            VARCHAR(200),
    COUNTRY_CODE       CHAR(2)         NOT NULL,
    BIZ_REG_NO         VARCHAR(50),
    ADDRESS            VARCHAR(500),
    DEFAULT_CURRENCY   CHAR(3)         DEFAULT 'USD' NOT NULL,
    DEFAULT_INCOTERMS  VARCHAR(10)     DEFAULT 'FOB',
    PAYMENT_TERMS_CODE VARCHAR(20)     DEFAULT 'TT_30' NOT NULL,
    PAYMENT_DAYS       INT             DEFAULT 30,
    ADVANCE_RATE       DECIMAL(5,2)    DEFAULT 30,
    QUOTE_VALID_DAYS   INT             DEFAULT 30 NOT NULL,
    CREDIT_LIMIT       DECIMAL(18,2),
    STATUS             VARCHAR(20)     DEFAULT 'ACTIVE' NOT NULL,
    REMARK             VARCHAR(1000),
    CREATED_BY         VARCHAR(50),
    CREATED_AT         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR(50),
    UPDATED_AT         TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID),
    UNIQUE KEY UK_CUSTOMER_CODE (CUSTOMER_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CUSTOMER_CONTACT (
    CONTACT_ID  BIGINT          NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID BIGINT          NOT NULL,
    NAME        VARCHAR(100)    NOT NULL,
    EMAIL       VARCHAR(150),
    PHONE       VARCHAR(50),
    POSITION    VARCHAR(50),
    MAIN_YN     CHAR(1)         DEFAULT 'N' NOT NULL,
    PRIMARY KEY (CONTACT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRODUCT (
    PRODUCT_ID   BIGINT          NOT NULL AUTO_INCREMENT,
    PRODUCT_CODE VARCHAR(50)     NOT NULL,
    NAME_EN      VARCHAR(200)    NOT NULL,
    NAME_KO      VARCHAR(200),
    SPEC         VARCHAR(500),
    HS_CODE      VARCHAR(20),
    UNIT         VARCHAR(10)     DEFAULT 'EA' NOT NULL,
    MOQ          DECIMAL(15,3),
    PACKAGE_TYPE VARCHAR(50),
    QTY_PER_CTN  INT,
    NET_WEIGHT   DECIMAL(15,3),
    GROSS_WEIGHT DECIMAL(15,3),
    CBM          DECIMAL(15,4),
    STATUS       VARCHAR(20)     DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY   VARCHAR(50),
    CREATED_AT   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_ID),
    UNIQUE KEY UK_PRODUCT_CODE (PRODUCT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRICE_HISTORY (
    PRICE_ID    BIGINT          NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID BIGINT,
    PRODUCT_ID  BIGINT          NOT NULL,
    CURRENCY    CHAR(3)         DEFAULT 'USD' NOT NULL,
    UNIT_PRICE  DECIMAL(18,4)   NOT NULL,
    INCOTERMS   VARCHAR(10),
    MIN_QTY     DECIMAL(15,3)   DEFAULT 0,
    VALID_FROM  DATE            NOT NULL,
    VALID_TO    DATE,
    REMARK      VARCHAR(500),
    CREATED_BY  VARCHAR(50),
    CREATED_AT  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (PRICE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_PRICE_PERIOD CHECK (VALID_TO IS NULL OR VALID_TO >= VALID_FROM),
    INDEX IX_PRICE_LOOKUP (PRODUCT_ID, CUSTOMER_ID, VALID_FROM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE INVENTORY (
    PRODUCT_ID    BIGINT          NOT NULL,
    ON_HAND_QTY   DECIMAL(15,3)   DEFAULT 0 NOT NULL,
    ALLOCATED_QTY DECIMAL(15,3)   DEFAULT 0 NOT NULL,
    SAFETY_QTY    DECIMAL(15,3)   DEFAULT 0 NOT NULL,
    VERSION       BIGINT          DEFAULT 0 NOT NULL,
    UPDATED_AT    TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_INVENTORY_QTY CHECK (ON_HAND_QTY >= 0 AND ALLOCATED_QTY >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE INVENTORY_TXN (
    TXN_ID     BIGINT          NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT          NOT NULL,
    TXN_TYPE   VARCHAR(20)     NOT NULL,
    QTY        DECIMAL(15,3)   NOT NULL,
    BEFORE_QTY DECIMAL(15,3),
    AFTER_QTY  DECIMAL(15,3),
    REF_TYPE   VARCHAR(20),
    REF_ID     BIGINT,
    REMARK     VARCHAR(500),
    CREATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (TXN_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    INDEX IX_INV_TXN_PROD (PRODUCT_ID, CREATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ====================================================================
-- 4. 트랜잭션 테이블 (견적, 수주, 출하, 인보이스, 입금)
-- ====================================================================
CREATE TABLE QUOTATION (
    QUOTATION_ID        BIGINT          NOT NULL AUTO_INCREMENT,
    QUOTE_NO            VARCHAR(40)     NOT NULL,
    REV_NO              INT             DEFAULT 0 NOT NULL,
    ORIGIN_QUOTATION_ID BIGINT,
    CUSTOMER_ID         BIGINT          NOT NULL,
    QUOTE_DATE          DATE            NOT NULL,
    VALID_UNTIL         DATE            NOT NULL,
    CURRENCY            CHAR(3)         DEFAULT 'USD' NOT NULL,
    INCOTERMS           VARCHAR(10),
    PORT_OF_LOADING     VARCHAR(100),
    PORT_OF_DISCHARGE   VARCHAR(100),
    PAYMENT_TERMS_CODE  VARCHAR(20),
    TOTAL_AMOUNT        DECIMAL(18,2)   DEFAULT 0 NOT NULL,
    EXCHANGE_RATE       DECIMAL(15,4),
    STATUS              VARCHAR(20)     DEFAULT 'DRAFT' NOT NULL,
    REMARK              VARCHAR(2000),
    SALES_MEMBER_ID     BIGINT,
    CREATED_BY          VARCHAR(50),
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR(50),
    UPDATED_AT          TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (QUOTATION_ID),
    UNIQUE KEY UK_QUOTATION_NO (QUOTE_NO),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (ORIGIN_QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID),
    CONSTRAINT CK_QUOTATION_STATUS CHECK (STATUS IN ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','SUPERSEDED')),
    INDEX IX_QUOTATION_CUS (CUSTOMER_ID, QUOTE_DATE DESC),
    INDEX IX_QUOTATION_ST (STATUS, VALID_UNTIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE QUOTATION_ITEM (
    ITEM_ID      BIGINT          NOT NULL AUTO_INCREMENT,
    QUOTATION_ID BIGINT          NOT NULL,
    LINE_NO      INT             NOT NULL,
    PRODUCT_ID   BIGINT          NOT NULL,
    QTY          DECIMAL(15,3)   NOT NULL,
    UNIT_PRICE   DECIMAL(18,4)   NOT NULL,
    AMOUNT       DECIMAL(18,2)   NOT NULL,
    REMARK       VARCHAR(500),
    PRIMARY KEY (ITEM_ID),
    UNIQUE KEY UK_QUOTATION_LINE (QUOTATION_ID, LINE_NO),
    FOREIGN KEY (QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_QI_QTY CHECK (QTY > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SALES_ORDER (
    ORDER_ID           BIGINT          NOT NULL AUTO_INCREMENT,
    ORDER_NO           VARCHAR(40)     NOT NULL,
    QUOTATION_ID       BIGINT,
    CUSTOMER_ID        BIGINT          NOT NULL,
    ORDER_DATE         DATE            NOT NULL,
    REQUIRED_DATE      DATE,
    CURRENCY           CHAR(3)         DEFAULT 'USD' NOT NULL,
    INCOTERMS          VARCHAR(10),
    PORT_OF_LOADING    VARCHAR(100),
    PORT_OF_DISCHARGE  VARCHAR(100),
    PAYMENT_TERMS_CODE VARCHAR(20),
    PAYMENT_DAYS       INT,
    TOTAL_AMOUNT       DECIMAL(18,2)   DEFAULT 0 NOT NULL,
    STATUS             VARCHAR(20)     DEFAULT 'CONFIRMED' NOT NULL,
    PO_NO              VARCHAR(50),
    REMARK             VARCHAR(2000),
    SALES_MEMBER_ID    BIGINT,
    CREATED_BY         VARCHAR(50),
    CREATED_AT         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR(50),
    UPDATED_AT         TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ORDER_ID),
    UNIQUE KEY UK_SALES_ORDER_NO (ORDER_NO),
    UNIQUE KEY UK_SO_QUOTATION (QUOTATION_ID),
    FOREIGN KEY (QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT CK_SO_STATUS CHECK (STATUS IN ('CONFIRMED','IN_PRODUCTION','PARTIALLY_SHIPPED','SHIPPED','CLOSED','CANCELLED')),
    INDEX IX_SO_CUS (CUSTOMER_ID, ORDER_DATE DESC),
    INDEX IX_SO_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SALES_ORDER_ITEM (
    ITEM_ID     BIGINT          NOT NULL AUTO_INCREMENT,
    ORDER_ID    BIGINT          NOT NULL,
    LINE_NO     INT             NOT NULL,
    PRODUCT_ID  BIGINT          NOT NULL,
    ORDERED_QTY DECIMAL(15,3)   NOT NULL,
    SHIPPED_QTY DECIMAL(15,3)   DEFAULT 0 NOT NULL,
    UNIT_PRICE  DECIMAL(18,4)   NOT NULL,
    AMOUNT      DECIMAL(18,2)   NOT NULL,
    REMARK      VARCHAR(500),
    PRIMARY KEY (ITEM_ID),
    UNIQUE KEY UK_SO_ITEM_LINE (ORDER_ID, LINE_NO),
    FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_SOI_SHIPPED CHECK (SHIPPED_QTY >= 0 AND SHIPPED_QTY <= ORDERED_QTY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SHIPMENT (
    SHIPMENT_ID             BIGINT          NOT NULL AUTO_INCREMENT,
    SHIPMENT_NO             VARCHAR(40)     NOT NULL,
    ORDER_ID                BIGINT          NOT NULL,
    TRANSPORT_MODE          VARCHAR(10)     DEFAULT 'OCEAN' NOT NULL,
    SHIP_DATE               DATE,
    ETD                     DATE,
    ETA                     DATE,
    VESSEL_NAME             VARCHAR(100),
    VOYAGE_NO               VARCHAR(50),
    BL_NO                   VARCHAR(50),
    CONTAINER_NO            VARCHAR(50),
    SEAL_NO                 VARCHAR(50),
    CONTAINER_TYPE          VARCHAR(20),
    AWB_NO                  VARCHAR(50),
    FLIGHT_NO               VARCHAR(50),
    AIRLINE                 VARCHAR(100),
    PORT_OF_LOADING         VARCHAR(100),
    PORT_OF_DISCHARGE       VARCHAR(100),
    SHIPPING_MARKS          LONGTEXT,
    TOTAL_NET_WEIGHT        DECIMAL(15,3),
    TOTAL_GROSS_WEIGHT      DECIMAL(15,3),
    TOTAL_CHARGEABLE_WEIGHT DECIMAL(15,3),
    TOTAL_CBM               DECIMAL(15,4),
    TOTAL_CARTON            INT,
    STATUS                  VARCHAR(20)     DEFAULT 'PLANNED' NOT NULL,
    REMARK                  VARCHAR(1000),
    CREATED_BY              VARCHAR(50),
    CREATED_AT              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY              VARCHAR(50),
    UPDATED_AT              TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SHIPMENT_ID),
    UNIQUE KEY UK_SHIPMENT_NO (SHIPMENT_NO),
    FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ORDER_ID),
    CONSTRAINT CK_SHIPMENT_STATUS CHECK (STATUS IN ('PLANNED','PACKED','SHIPPED','ARRIVED','CANCELLED')),
    CONSTRAINT CK_SHIPMENT_MODE   CHECK (TRANSPORT_MODE IN ('OCEAN','AIR')),
    CONSTRAINT CK_SHIPMENT_DOC CHECK (
        STATUS <> 'SHIPPED'
        OR (TRANSPORT_MODE = 'OCEAN' AND BL_NO  IS NOT NULL)
        OR (TRANSPORT_MODE = 'AIR'   AND AWB_NO IS NOT NULL)
    ),
    INDEX IX_SHIPMENT_ORD (ORDER_ID),
    INDEX IX_SHIPMENT_ETD (ETD, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SHIPMENT_ITEM (
    ITEM_ID       BIGINT          NOT NULL AUTO_INCREMENT,
    SHIPMENT_ID   BIGINT          NOT NULL,
    ORDER_ITEM_ID BIGINT          NOT NULL,
    PRODUCT_ID    BIGINT          NOT NULL,
    QTY           DECIMAL(15,3)   NOT NULL,
    CARTON_QTY    INT,
    NET_WEIGHT    DECIMAL(15,3),
    GROSS_WEIGHT  DECIMAL(15,3),
    CBM           DECIMAL(15,4),
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT(SHIPMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ORDER_ITEM_ID) REFERENCES SALES_ORDER_ITEM(ITEM_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE INVOICE (
    INVOICE_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    INVOICE_NO         VARCHAR(40)     NOT NULL,
    INVOICE_TYPE       VARCHAR(10)     NOT NULL,
    QUOTATION_ID       BIGINT,
    ORDER_ID           BIGINT,
    SHIPMENT_ID        BIGINT,
    ISSUE_DATE         DATE            NOT NULL,
    DUE_DATE           DATE            NOT NULL,
    CURRENCY           CHAR(3)         NOT NULL,
    AMOUNT             DECIMAL(18,2)   NOT NULL,
    RATE_BASE_DATE     DATE,
    EXCHANGE_RATE      DECIMAL(15,4),
    KRW_AMOUNT         DECIMAL(18,2),
    PAID_AMOUNT        DECIMAL(18,2)   DEFAULT 0 NOT NULL,
    STATUS             VARCHAR(20)     DEFAULT 'ISSUED' NOT NULL,
    PAYMENT_TERMS_CODE VARCHAR(20),
    PAYMENT_METHOD     VARCHAR(20),
    LC_NO              VARCHAR(50),
    LC_DATE            DATE,
    BANK_INFO          VARCHAR(500),
    PUBLIC_TOKEN       VARCHAR(64),
    CREATED_BY         VARCHAR(50),
    CREATED_AT         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY         VARCHAR(50),
    UPDATED_AT         TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (INVOICE_ID),
    UNIQUE KEY UK_INVOICE_NO (INVOICE_NO),
    UNIQUE KEY UK_INVOICE_TOKEN (PUBLIC_TOKEN),
    FOREIGN KEY (QUOTATION_ID) REFERENCES QUOTATION(QUOTATION_ID),
    FOREIGN KEY (ORDER_ID)    REFERENCES SALES_ORDER(ORDER_ID),
    FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT(SHIPMENT_ID),
    CONSTRAINT CK_INVOICE_TYPE   CHECK (INVOICE_TYPE IN ('PI','CI')),
    CONSTRAINT CK_INVOICE_STATUS CHECK (STATUS IN ('ISSUED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED')),
    CONSTRAINT CK_INVOICE_CI CHECK (INVOICE_TYPE <> 'CI' OR (SHIPMENT_ID IS NOT NULL AND ORDER_ID IS NOT NULL)),
    CONSTRAINT CK_INVOICE_PI CHECK (INVOICE_TYPE <> 'PI' OR (QUOTATION_ID IS NOT NULL OR ORDER_ID IS NOT NULL)),
    INDEX IX_INVOICE_DUE (DUE_DATE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PAYMENT (
    PAYMENT_ID BIGINT          NOT NULL AUTO_INCREMENT,
    INVOICE_ID BIGINT          NOT NULL,
    PAID_DATE  DATE            NOT NULL,
    AMOUNT     DECIMAL(18,2)   NOT NULL,
    CURRENCY   CHAR(3)         NOT NULL,
    METHOD     VARCHAR(20),
    BANK_REF   VARCHAR(100),
    REMARK     VARCHAR(500),
    CREATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    CONSTRAINT CK_PAYMENT_AMOUNT CHECK (AMOUNT > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ====================================================================
-- 5. 부속 테이블 (첨부파일, 환율, 알림, 문서번호)
-- ====================================================================
CREATE TABLE ATTACHMENT (
    ATTACHMENT_ID BIGINT          NOT NULL AUTO_INCREMENT,
    REF_TYPE      VARCHAR(20)     NOT NULL,
    REF_ID        BIGINT          NOT NULL,
    DOC_TYPE      VARCHAR(20),
    ORIG_NAME     VARCHAR(255)    NOT NULL,
    STORED_NAME   VARCHAR(255)    NOT NULL,
    FILE_PATH     VARCHAR(500)    NOT NULL,
    CONTENT_TYPE  VARCHAR(100),
    FILE_SIZE     BIGINT          NOT NULL,
    CREATED_BY    VARCHAR(50),
    CREATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ATTACHMENT_ID),
    CONSTRAINT CK_ATTACHMENT_REF CHECK (REF_TYPE IN ('QUOTATION','SALES_ORDER','SHIPMENT','INVOICE')),
    INDEX IX_ATTACHMENT_REF (REF_TYPE, REF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EXCHANGE_RATE (
    RATE_ID     BIGINT          NOT NULL AUTO_INCREMENT,
    BASE_DATE   DATE            NOT NULL,
    CUR_UNIT    VARCHAR(10)     NOT NULL,
    CUR_NAME    VARCHAR(50),
    DEAL_BAS_R  DECIMAL(15,4)   NOT NULL,
    TTB         DECIMAL(15,4),
    TTS         DECIMAL(15,4),
    SOURCE      VARCHAR(30)     DEFAULT 'KOREAEXIM' NOT NULL,
    FETCHED_AT  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (RATE_ID),
    UNIQUE KEY UK_EXCHANGE_RATE (BASE_DATE, CUR_UNIT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE NOTIFICATION (
    NOTIF_ID   BIGINT          NOT NULL AUTO_INCREMENT,
    MEMBER_ID  BIGINT          NOT NULL,
    NOTIF_TYPE VARCHAR(30)     NOT NULL,
    TITLE      VARCHAR(200)    NOT NULL,
    MESSAGE    VARCHAR(1000),
    REF_TYPE   VARCHAR(20),
    REF_ID     BIGINT,
    READ_YN    CHAR(1)         DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (NOTIF_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    INDEX IX_NOTIF_MEMBER (MEMBER_ID, READ_YN, NOTIF_ID DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DOC_NUMBER (
    DOC_TYPE      VARCHAR(20)    NOT NULL,
    CUSTOMER_CODE VARCHAR(8)     NOT NULL,
    YEAR_VAL      INT            NOT NULL,
    LAST_SEQ      INT            DEFAULT 0 NOT NULL,
    PRIMARY KEY (DOC_TYPE, CUSTOMER_CODE, YEAR_VAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ====================================================================
-- 6. 초기 데이터 INSERT
-- ====================================================================
INSERT INTO BOARD (BOARD_CODE, BOARD_NAME, AUTH_READ, AUTH_WRITE, FILE_YN, COMMENT_YN, LIKE_YN, PAGE_SIZE, SORT_ORDER)
VALUES ('FREE', '공지·문의', 'ALL', 'ALL', 'N', 'N', 'Y', 10, 1);

INSERT INTO BOARD (BOARD_CODE, BOARD_NAME, AUTH_READ, AUTH_WRITE, FILE_YN, COMMENT_YN, LIKE_YN, PAGE_SIZE, SORT_ORDER)
VALUES ('QNA', '거래처 Q&A', 'MEMBER', 'MEMBER', 'N', 'Y', 'Y', 10, 2);

INSERT INTO BOARD (BOARD_CODE, BOARD_NAME, AUTH_READ, AUTH_WRITE, FILE_YN, COMMENT_YN, LIKE_YN, PAGE_SIZE, SORT_ORDER)
VALUES ('ARCHIVE', '자료실', 'MEMBER', 'MEMBER', 'Y', 'Y', 'Y', 10, 3);

-- 관리자 계정 (비밀번호는 BCrypt로 'password' 해시)
INSERT INTO MEMBER (LOGIN_ID, PASSWORD, NAME, EMAIL, PHONE, ROLE, EMAIL_VERIFIED_YN, STATUS)
VALUES ('admin', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', '관리자', 'admin@example.com', '010-0000-0000', 'ADMIN', 'Y', 'ACTIVE');

COMMIT;
